version: '3.8'

services:
  frontend:
    build:
      context: ./client
    image: grad_site_ideas_frontend
    ports:
      - "443:443"
    depends_on:
      - backend
#Last
  backend:
    build:
      context: ./server
    image: grad_site_ideas_backend
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
