version: '3.8'

services:
  frontend:
    build:
      context: ./client
    image: omartamer12/grad_site_ideas:frontend
    ports:
      - "443:443"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    image: omartamer12/grad_site_ideas:backend
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
