version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
