# .github/workflows/docker-image.yml
name: Docker Image CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
# Build and push client Docker image
    - name: Build and push client Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./client
        file: ./client/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/grad_idea_client:latest
          ghcr.io/${{ github.repository_owner }}/grad_idea_client:${{ github.sha }}

    # Build and push server Docker image
    - name: Build and push server Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/grad_idea_server:latest
          ghcr.io/${{ github.repository_owner }}/grad_idea_server:${{ github.sha }}
